further fixes to the Makefile.am
pnkfelix/krabcake-vg pull request #23
Opened 2023-05-25 15:33 UTC by pnkfelix

further fixes to the Makefile.am

hopefully this one works better for all of us.

the main changes were:

1. unified the rule into one place. Before, if you did `make -jN`, it would quite easily attempt to call `rustup toolchain install nightly` *twice in parallel*, which was quite bad (not just in terms of performance; I don't think the `rustup` tool itself is designed to handle that scenario at all).
2. got rid of checking if we're running under CI. I think the check being done here applies reasonably well to either CI or nor CI context, and the CI checking as implemented was not shell-independent. (If we really want to do that inspection of an env var, we can do it in the makefile syntax itself, and e.g. make the rule recipe depend on the presence/absence of that variable)

2023-05-25 15:33 UTC, pnkfelix commented
r? @bryangarza

2023-05-25 15:38 UTC, bryangarza approved these changes

2023-05-25 15:39 UTC, bryangarza requested changes
Seems CI is not passing

2023-05-26 16:49 UTC, pnkfelix commented
> Seems CI is not passing

I bet I know what's wrong, I bet I need to `mkdir -p` the directory before I touch a file in it. Let me try with that change.

2023-05-26 17:01 UTC, bryangarza approved these changes

2023-05-26 17:01 UTC, merged